### ISSUE TITLE
Dear Vladislav Kurshakov

### ISSUE THREAD

**Issue by zhongchangming** [vakurshakov/xpic#1]
Dear Vladislav Kurshakov：
Sorry to bother you, but recently I've been browsing and following one of your previous projects: https://github.com/vakurshakov/petsc-wrapper, and many of the implementations inspired me a lot. Unfortunately, today I found out that you deleted the project. I'm sorry to hear that,  but I was wondering if you could provide me with a copy of the project so that I can study it again. Thank you very much!

**Comment by vakurshakov** [comment]
Hello! It's interesting to hear that) I've reverted the visibility of the [petsc-wrapper](https://github.com/vakurshakov/petsc-wrapper) repository to `public`. Me and my colleague was planning to use this in xpic, but I quickly understood that for now it would be easier to use raw C-style with PETSc. Pull requests are welcome!)

**Comment by zhongchangming** [comment]
Thank you for your reply, I am also looking at the rest of your projects e.g. xpic, unfortunately, I am not sure what this project was developed for. I wonder if you could provide me with some of your published project-related articles so that I can follow up with references to your work, thanks again for your help, and good luck with your work. （I am a PhD student from China）
